Repository elastic/opbeans-ruby, pull requests merged in 2020-01, with the labels that each got.

#38 fix: agent version is matching the tag name
  .ci/bump-version.sh
Labels: automation, bug

#34 feat: bump Agent Ruby version to 3.2.0
  Gemfile.lock
Labels: automation, dependencies

#33 feat: bump Agent Ruby version to 3.3.0
  Gemfile.lock
Labels: automation, dependencies

#39 Add debug output when failing the git diff
  .ci/bump-version.sh
Labels: automation, enhancement
